#!/bin/bash
# Usage:
#    ./docker-run   enter into container with bash
#    ./docker-run <command> run a command in the container

if [[ $# -eq 1 ]]; then
  cmd="bash"
else
  cmd="$@"
fi

docker run -it --rm -v `pwd`:/mnt -w /mnt \
    --cap-add=SYS_PTRACE\
    --security-opt='seccomp=unconfined'\
    --tmpfs=/tmp/tmpfs:rw,size=500m,mode=1777\
     dqneo/ubuntu-compiler-go $cmd

# Change prompt in the container
# export PS1='docker:\W $ '
