#!/bin/bash
# Usage:
#    ./docker-run   enter into container with bash
#    ./docker-run <command> run a command in the container

if [[ $# -eq 1 ]]; then
  cmd="bash"
else
  cmd="$@"
fi

docker run \
    -it --rm\
    -v `pwd`:/mnt -w /mnt \
    --cap-add=SYS_PTRACE\
    --security-opt='seccomp=unconfined'\
    --env PATH=/usr/lib/go-1.15/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\
    --env GOPATH=/root/go \
    --tmpfs=/tmp/tmpfs:rw,size=500m,mode=1777\
     dqneo/ubuntu-build-essential:go $cmd

# Change prompt in the container
# export PS1='docker:\W $ '
